resnet/urls.py
from resnet_app import views
from django.conf.urls.defaults import *
from django.contrib.auth.views import login, logout
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'resnet_app.views.index'),
    # url(r'^resnet/', include('resnet.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cpanel/$', 'resnet_app.views.cpanel'),
    url(r'^cpanel/open', 'resnet_app.views.cpanel_open'),
    url(r'^cpanel/submit', 'resnet_app.views.cpanel_submit'),
    url(r'^accounts/login/$', login),
    url(r'^accounts/logout/$', logout),
    url(r'^accounts/profile/$', views.redirect_to_report),
    url(r'^reports/$', 'resnet_app.views.profile'),
    url(r'^reports/(?P<reportID>[^\.]+)', 
               'resnet_app.views.view_report'),
    url(r'^devices/find/', 'resnet_app.views.find_device'),
    url(r'^search/', 'resnet_app.views.search'),
    url(r'^cpanel/add_status/', 'resnet_app.views.add_status'),
    url(r'^cpanel/save_status/', 'resnet_app.views.save_status'),
)

resnet_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Device(models.Model):
	DEVICE_CHOICES = (
		("l", "Laptop"),
		("d", "Desktop"),
		("m", "Mobile"),
	)
	OS_CHOICES = (
		("wx", "Windows XP"),
		("w7", "Windows 7"),
		("w8", "Windows 8"),
		("mc", "Mac OS X"),
		("io", "iOS"),
		("an", "Android"),
		("bb", "BlackBerry"),
		("wp", "Windows Phone"),
		("ot", "Other"),
	)
	owner = models.ForeignKey(User, db_index=True)
	type = models.CharField(max_length=2, choices=DEVICE_CHOICES, db_index=True)
	os = models.CharField(max_length=2, choices=OS_CHOICES, db_index=True)
	username = models.CharField(max_length=100, null=True, blank=True)
	password = models.CharField(max_length=100, null=True, blank=True)
	serial = models.CharField(max_length=100, null=True, blank=True)
	
	def __unicode__(self):
		return '%s\'s %s' %(self.owner.username, self.get_type_display())
	
	def get_os_choices(self):
		return self.OS_CHOICES;
	
	def get_device_choices(self):
		return self.DEVICE_CHOICES;

class Report(models.Model):
	PROBLEM_CHOICES = (
		("hw", "Hardware Repair"),
		("v", "Virus"),
		("n", "Network"),
	)
	owner = models.ForeignKey(User, db_index=True)
	device = models.ForeignKey('Device', db_index=True)
	problem = models.CharField(max_length=100, choices=PROBLEM_CHOICES, db_index=True)
	description = models.TextField()
	completed = models.BooleanField()
	createdAt = models.DateTimeField(auto_now=True)
	updatedAt = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return '%s\'s %s - %s' %(self.owner.username, self.device.get_type_display(), self.problem)
	
	def get_problem_choices(self):
		return self.PROBLEM_CHOICES;

class Report_Tech(models.Model):
	report = models.ForeignKey('Report', db_index=True)
	tech = models.ForeignKey(User, db_index=True)

class Status(models.Model):
	MESSAGE_CHOICES = (
		("c", "Checked In"),
		("i", "In Progress"),
		("f", "Fixed"),
		("n", "User Notified"),
		("p", "Picked Up")
	)
	tech = models.ForeignKey(User, db_index=True)
	report = models.ForeignKey('Report', db_index=True)
	message = models.CharField(max_length=1, choices=MESSAGE_CHOICES)
	note = models.TextField()
	createdAt = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return '%s\'s %s - %s - %s' %(self.report.owner.username, self.report.device.get_type_display(), self.report.problem, self.get_message_display())

	def get_message_choices(self):
		return self.MESSAGE_CHOICES

class Notification(models.Model):
	NOTIFICATION_TYPES = (
		("p", "Phone Call"),
		("s", "SMS"),
		("e", "Email"),
	)
	tech = models.ForeignKey(User, db_index=True)
	report = models.ForeignKey('Report', db_index=True)
	type = models.CharField(max_length=20)
	notes = models.TextField()
	createdAt = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return '%s\'s %s to %s' %(self.tech.username, self.get_type_display(), self.report.owner.username)

resnet_app/views.py
# Create your views here.
import datetime

from resnet_search import normalize_query, get_query
from models import User,Device, Report, Report_Tech, Status, Notification
from django.contrib import auth
from django.conf import settings
from django.utils import simplejson
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render_to_response, get_object_or_404

def index(request):
	user = request.user
	reports = Report.objects.filter(completed=False).order_by('-createdAt')
	reports_length = len(reports)
	now = datetime.datetime.now()
	now_day = now.strftime("%A")
	return render_to_response('index.html', {
		'user' : user,
		'reports' : reports,
		'reports_length' : reports_length,
		'now' : now,
		'now_day' : now_day,
		'active':'index',
	})

def login_view(request):
	username = request.POST.post('username', '')
	password = request.POST.post('password', '')
	user = auth.authenticate(username=username, password=password)
	if user is not None and user.is_active:
		# Correct password, and the user is marked "active"
		auth.login(request, user)
		# Redirect to a success page.
		return render_to_response("/account/loggedin/", context_instance=RequestContext(request))
	else:
		# Show an error page
		return render_to_response("/account/invalid/", context_instance=RequestContext(request))

def logout_view(request):
	auth.logout(request)
	# Redirect to a success page.
	return render_to_response("/reports/")

@login_required(login_url='/accounts/login/')
def profile(request):
	user = request.user
	reports = Report.objects.filter(owner=user).order_by('-createdAt')
	devices = Device.objects.filter(owner=user)
	statuses = {}
	for report in reports:
		statuses[report.id] = Status.objects.filter(report=report).order_by('-createdAt')
	latest_statuses = {}
	for report in reports:
		if statuses[report.id]:
			latest_statuses[report.id] = statuses[report.id][0]
	return render_to_response('profile.html', {
		'user' : user,
		'reports' : reports,
		'devices' : devices,
		'active' : 'status',
		'statuses' : statuses,
		'latest_statuses' : latest_statuses,
	})

def office_status(request):
	user = request.user
	reports = Report.objects.filter(completed=False).order_by('-createdAt')
	reports_length = len(reports)
	now = datetime.datetime.now()
	now_day = now.strftime("%A")
	is_open = False
	if (now.hour > 10 and now.hour < 19 and now_day != 'Friday') or (now.hour > 10 and now.hour < 17 and now_day == 'Friday'):
		is_open = True
	return render_to_response('office_status.html', {
		'user' : user,
		'reports' : reports,
		'reports_length' : reports_length,
		'now' : now,
		'now_day' : now_day,
		'active':'office',
		'open' : is_open,
	})

@login_required(login_url='/accounts/login/')
def view_report(request, reportID):
	report = get_object_or_404(Report, id=reportID)
	user = request.user
	statuses = Status.objects.filter(report_id=reportID).order_by('-createdAt')
	latest = ''
	if statuses:
		latest = statuses[0]
	if report:
		if (report.owner.id == user.id) or user.is_staff:
			return render_to_response('view_report.html', {
				'user' : user,
				'report' : report,
				'statuses' : statuses,
				'latest' : latest,
				'active' : 'status',
			}, context_instance=RequestContext(request))
		else:
			redirect_to_report
	else:
		return redirect_to_report

@staff_member_required
def cpanel(request, success = False):
	user = request.user
	reports = Report.objects.all()
	open_reports = reports.filter(completed = False)
	closed_reports = reports.filter(completed = True)
	open = len(open_reports)
	closed = len(closed_reports)
	numReports = len(reports)
	return render_to_response('cpanel/cpanel.html', {
		'report' : reports,
		'numReports' : numReports,
		'user' : user,
		'open_reports' : open_reports,
		'closed_reports' : closed_reports,
		'open' : open,
		'closed' : closed,
		'active' : 'index',
		'success' : success,
	}, context_instance=RequestContext(request))

@staff_member_required
def cpanel_open(request):
	user = request.user
	device_choices = Device.get_device_choices(Device())
	os_choices = Device.get_os_choices(Device())
	problem_choices = Report.get_problem_choices(Report())
	return render_to_response('cpanel/open.html', {
			'user' : user,
			'device_choices' : device_choices,
			'os_choices' : os_choices,
			'problem_choices' : problem_choices
			}, context_instance=RequestContext(request))

@login_required
def cpanel_submit(request):
	# The user adding the request
	user = request.user

	name = request.POST['name']
	phone = request.POST['phone']
	email = request.POST['email']
	type = request.POST['device']
	os = request.POST['os']
	problem = request.POST['problem']
	description = request.POST['description']
	deviceObj = Device()
	report = Report()
	usersWithSameEmail = User.objects.filter(email=email)
	reportUser = User()

	userFound = False
	for u in usersWithSameEmail:
		# If user exists, don't create a new one
		if u.email == email:
			reportUser = u
			userFound = True

	if not userFound:
		reportUser.email = email
		reportUser.username = name
		reportUser.password = 'password'
		reportUser.save()

	# Get the devices the user has
	usersDevices = Device.objects.filter(owner=reportUser)

	deviceFound = False
	for d in usersDevices:
		# If the device exists recognize it, and use it
		if d.os == os and d.type == type:
			deviceObj = d
			deviceFound = True

	if not deviceFound:
		# Generate device object
		deviceObj.owner = reportUser
		deviceObj.os = os
		deviceObj.type = type
		deviceObj.save()

	# Generate Report
	report.owner = reportUser
	report.device = deviceObj
	report.description = description
	report.problem = problem
	report.completed = False
	report.save()

	# Generate initial status
	status = Status()
	status.report = report
	# Checked in message
	status.message = 'c'
	status.tech = user
	status.save()

	return cpanel(request, True)

@login_required
def find_device(request):
	if request.is_ajax():
		id = request.POST['id']
		device = Device.objects.get(id=id)
		if (device.owner.id == request.user.id) or (request.user.is_staff):
			reports = Report.objects.filter(device=device)
			if device:
				return render_to_response('device_modal.html', {
					'device' : device,
					'reports' : reports,
				})
		else:
			redirect_to_report
	else:
		return 'error'

@staff_member_required
def search(request):
	user = request.user
	query_string = ''
	found_entries = None
	if request.POST['q'].strip():
		query_string = request.POST['q']
		entry_query = get_query(query_string, ['problem', 'description', 'owner__username', 'owner__email', 'owner__first_name', 'owner__last_name'])
		found_entries = Report.objects.filter(entry_query)

	return render_to_response('search_results.html', {
		'query_string': query_string,
		'found_entries': found_entries,
		'user' : user,
	}, context_instance=RequestContext(request))

@staff_member_required
def add_status(request):
	id = request.POST['id']
	user = request.user
	report = Report.objects.get(id=id)
	statuses = Status.objects.filter(report=report).order_by('-createdAt')
	message_choices = Status.get_message_choices(Status())
	return render_to_response('cpanel/add_status.html', {
		'report' : report,
		'statuses' : statuses,
		'message_choices' : message_choices,
		'user' : user,
	}, context_instance=RequestContext(request))

def save_status(request):
	id = request.POST['id']
	report = Report.objects.get(id=id)
	message = request.POST['message']
	note = request.POST['note']
	user = request.user
	new_status = Status()
	new_status.tech = user
	new_status.report = report
	new_status.message = message
	new_status.note = note
	new_status.save()

	if message == 'p':
		report.completed = True
		report.save()

	return HttpResponseRedirect('/reports/' + id)


def redirect_to_report(request):
	return HttpResponseRedirect('/reports/')

resnet_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="author" content="Bob Nisco and Jason Parraga">
		<meta name="description" content="Marist College Hackathon Fall 2012 Project">

		<link rel="stylesheet" href="/static/css/bootstrap.min.css" />
		<link rel="stylesheet" href="/static/css/bootstrap-responsive.min.css" />
		<link rel="stylesheet" href="/static/css/include.css" />
		<title>ResNet</title>
	</head>

	<body>
		<div id="wrap">
			<div class="navbar navbar-inverse navbar-fixed-top">
				<div class="navbar-inner">
					<div class="container">
						<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</a>
						<a class="brand" href="/">ResNet Tracking</a>
						<div class="nav-collapse collapse">
							<ul class="nav">
								<li {% if active == 'index' %} class="active" {% endif %}><a href="/">Home</a></li>
								<li {% if active == 'status' %} class="active" {% endif %}><a href="/reports">Check Status</a></li>
								{% if user.is_staff %}
								<li><a href="/cpanel">Cpanel Home</a></li>
								{% endif %}
							</ul>
							<div class="pull-right">
							{% if user.is_authenticated %}
								<a href="/accounts/logout"><div class="btn"><i class="icon-user"></i> Logout</div></a>
							{% else %}
								<a href="/accounts/login"><div class="btn"><i class="icon-user"></i> Login</div></a>
							{% endif %}
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="container">
				<div class="wrapper">
					<div class="row">
						<div class="span12" id="content">
							{% block content %}
							{% endblock %}
						</div>
					</div>
				</div>
			</div>
			<div id="push"></div>
		</div>
		<footer class="footer">
			<div class="container">
				<p class="pull-right"><a href="#">Back to top</a></p>
				<p>Built by <a href="http://bobnisco.com" target="_blank">Bob Nisco</a> and <a href="http://jasonparraga.com" target="_blank">Jason Parraga</a> for Marist College Fall 2012 Hackathon | <a href="https://github.com/BobNisco/fall-2012-hackathon" target="_blank">Source on GitHub</a></p>
			</div>
		</footer>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
		<script type="text/javascript" charset="utf-8" src="/static/js/bootstrap.min.js"></script>
		<script type="text/javascript" charset="utf-8" src="/static/js/jquery.tablesorter.min.js"></script>
		<script type="text/javascript" charset="utf-8" src="/static/js/include.js"></script>
		<script type="text/javascript" charset="utf-8" src="/static/js/profile.js"></script>
	</body>
</html>

resnet_app/templates/device_modal.html
<div class="modal hide fade" id="device_modal_{{ device.id }}">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3>Device Details <small>{{ device }}</small></h3>
	</div>
	<div class="modal-body">
		{% if reports %}
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Problem</th>
					<th>Brought In</th>
					<th>Completed?</th>
				</tr>
			</thead>
			<tbody>
				{% for report in reports %}
				<tr>
					<td><a href="/reports/{{ report.id }}">{{ report.get_problem_display }}</a></td>
					<td>{{ report.createdAt }}</td>
					<td>{{ report.completed }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% else %}
		<p>There are no associated reports with this device. Nice!</p>
		{% endif %}
	</div>
</div>

resnet_app/templates/index.html
{% extends "base.html" %}

{% block content %}
	<div class="page-header">
		<h1>Current Office Status</h1>
	</div>
	<div>
		<p>There are currently <strong>{{ reports_length }}</strong> open reports being worked on by our technicians. {% if is_open %}Now is a {% if reports_length < 10 %}<span class="label label-success">great</span>{% elif reports_length > 10 and reports_length < 20 %}<span class="label label-warning">good</span>{% else %}<span class="label label-important">decent</span>{% endif %} time to bring in your device for a speedy repair.{% endif %}</p>
	</div>
	<div class="row">
		<div class="span4">
			{% if is_open %}
			<p>We are currently <span class="label label-success">open</span>.</p>
			{% else %}
			<p>Sorry, we are currently <span class="label label-important">closed</span>.</p>
			{% endif %}
			<legend>Hours of Operation</legend>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Day</th>
						<th>Open</th>
						<th>Close</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Monday</td>
						<td>10:00am</td>
						<td>7:00pm</td>
					</tr>
					<tr>
						<td>Tuesday</td>
						<td>10:00am</td>
						<td>7:00pm</td>
					</tr>
					<tr>
						<td>Wednesday</td>
						<td>10:00am</td>
						<td>7:00pm</td>
					</tr>
					<tr>
						<td>Thursday</td>
						<td>10:00am</td>
						<td>7:00pm</td>
					</tr>
					<tr>
						<td>Friday</td>
						<td>10:00am</td>
						<td>5:00pm</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
{% endblock %}

resnet_app/templates/profile.html
{% extends "base.html" %}

{% block content %}
    
    <div class="page-header">
        <h1>Welcome <small>{% if user.first_name or user.last_name %}{{ user.first_name }} {{ user.last_name }}{% else %}{{ user.username }}{% endif %}</small></h1>
    </div>
    <h3>Your Reports</h3>
    {% if reports %}
    <table class="table table-striped tablesorter">
        <thead>
            <tr>
                <th>Problem</th>
                <th>Device</th>
                <th>Brought In</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
        {% for report in reports %}
            <tr>
                <td><a href="{{report.id}}">{{ report.get_problem_display }}</a></td>
                <td>{{ report.device }}</td>
                <td>{{ report.createdAt }}</td>
                <td>{% if report.completed %}Completed{% else %}<a href="{{report.id}}">Check Status</a>{% endif %}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>You don't have any reports, congrats on staying safe!</p>
    {% endif %}
    <h3>Your Devices</h3>
    {% if devices %}
    <table class="table table-striped tablesorter">
        <thead>
            <tr>
                <th>Title</th>
                <th>Type</th>
                <th>OS</th>
                <th>Serial</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for device in devices %}
            <tr data-id="{{ device.id }}">
                <td>{{ device }}</td>
                <td>{{ device.get_type_display }}</td>
                <td>{{ device.get_os_display }}</td>
                <td>{{ device.serial }}</td>
                <td><a href="#" class="device_reports_link">View Associated Reports</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>You don't have any devices listed in our database. That's probably a good thing!</p>
    {% endif %}
{% endblock %}

resnet_app/templates/search_results.html
{% extends "cpanel/cpanelbase.html" %}

{% block content %}
<div class="page-header">
	<h1>Search Results <small>{{ query_string }}</small></h1>
</div>
<div>
{% if found_entries %}
<table class="table table-striped">
	<thead>
		<tr>
			<th>Report</th>
			<th>Owner</th>
			<th>Created</th>
			<th>Completed</th>
		</tr>
	</thead>
	<tbody>
		{% for entry in found_entries %}
		<tr>
			<td><a href="/reports/{{ entry.id }}">{{ entry.get_problem_display }}</a></td>
			<td>{{ entry.owner }}</td>
			<td>{{ entry.createdAt }}</td>
			<td>{{ entry.completed }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% else %}
<p>No results for query "{{ query_string }}"</p>
{% endif %}
</div>
{% endblock %}

resnet_app/templates/test.html
{{id}}
{{u}}

resnet_app/templates/view_report.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">
	<h1>Current Report Status: {{latest.get_message_display}}</h1>
</div>
<div class="view_report" data-id="{{ report.id }}">
    {% if report %}
    <div class="row">
    	<div class="span10 offset1">
    		<div class="progress progress-striped active">
    		{% if latest.message = "c" %}
	  			<div class="bar bar-danger" style="width: 10%;"></div>
	  		{% elif latest.message = "i" %}
	  			<div class="bar bar-warning" style="width: 50%;"></div>
	  		{% elif latest.message = "f" %}
	  			<div class="bar bar-info" style="width: 80%;"></div>
	  		{% elif latest.message = "n" %}
	  			<div class="bar bar-info" style="width: 90%;"></div>
	  		{% elif latest.message = "p" %}
	  			<div class="bar bar-success" style="width: 100%;"></div>
	  		{% endif %}
	  		</div>
	  		<p>
	  		Last updated {{latest.createdAt}}
			</p>
			<legend>Report Overview</legend>
    		<table class="table table-striped">
		        <tbody>
		            <tr>
		                <td><strong>Device</strong></td>
		                <td>{{ report.device.get_type_display }}</td>
		            </tr>
		            <tr>
		                <td><strong>Date Opened</strong></td>
		                <td>{{ report.createdAt }}</td>
		            </tr>
		            <tr>
		                <td><strong>Problem</strong></td>
		                <td>{{ report.get_problem_display }}</td>
		            </tr>
		            <tr>
		                <td><strong>Description</strong></td>
		                <td>{{ report.description }}</td>
		            </tr>
		        </tbody>
		    </table>

		    <legend>Status Updates {% if user.is_staff %}<form action="/cpanel/add_status/" method="post"> {% csrf_token %}<input type="hidden" name="id" value="{{ report.id }}" /><input type="submit" class="btn btn-primary pull-right" value="Add Status Update" /></form>{% endif %}</legend>
		    <table class="table table-striped tablesorter">
		    	<thead>
		    		<tr>
		    			<th>Message</th>
		    			<th>Details</th>
		    			<th>When</th>
		    			<th>Tech</th>
		    		</tr>
		    	</thead>
		    	<tbody>
		    		{% for status in statuses %}
		    		<tr>
		    			<td>{{ status.get_message_display }}</td>
		    			<td>{{ status.note }}</td>
		    			<td>{{ status.createdAt }}</td>
		    			<td>{{ status.tech.username }}</td>
		    		</tr>
		    		{% endfor %}
		    	</tbody>
		    </table>
    	</div>
    </div>
    {% endif %}
   </div>
{% endblock %}